# Generated by Django 2.2.2 on 2019-07-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190701_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
