# Generated by Django 2.2.2 on 2019-07-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190701_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
