# Generated by Django 2.2.2 on 2019-07-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190701_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='action',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='item',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
