# Generated by Django 2.2.2 on 2019-07-02 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190702_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.TextField(default='Test', max_length=100),
        ),
        migrations.AlterField(
            model_name='habit',
            name='item',
            field=models.TextField(default='Test', max_length=100),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_habits', to=settings.AUTH_USER_MODEL),
        ),
    ]
