# Generated by Django 2.2.3 on 2019-07-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190702_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.CharField(help_text='Enter your new goal above.', max_length=200, verbose_name=''),
        ),
    ]
